import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'
import Storage from "../firebase/storage/index"
import FireStore from '../firebase/firestore'
export default function index({ results, collection }) {
  return (
    <div>
      <Head>
        <title>Hulu Clone Zak's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      {/* NavBar */}
      <Nav />
      {/* Results */}
      <Results results={results} collection={collection} />
    </div>
  )
}

export async function getServerSideProps(context) {
  const index = context.query.collection
  const results = await (async () => {
    let videoArray = []
    await FireStore.Videos.GET.meta({ collection: index }).then((videos) => {
      if (videos) {
        for (let [key, value] of Object.entries(videos)) {
          videoArray.push(value)
        }
      }
    })
    return videoArray
  })()
  return {
    props: {
      results
    }
  }
}
